# Generated by Django 5.0.1 on 2024-01-20 10:00

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Eg: +234758849930', max_length=30, null=True, region='NG', verbose_name='Phone Number')),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10)),
                ('city', models.TextField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('home_address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Your Home Address')),
                ('delivery_address_1', models.TextField(blank=True, max_length=255, null=True, verbose_name='Delivery Address 1')),
                ('delivery_address_2', models.TextField(blank=True, max_length=255, null=True, verbose_name='Delivery Address 2')),
                ('country', django_countries.fields.CountryField(default='NG', max_length=2, verbose_name='Country')),
                ('profile_photo', models.ImageField(default='default.jpg', upload_to='profile_images', verbose_name='Profile Photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
