# Generated by Django 5.0.1 on 2024-02-17 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_city_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='delivery_address_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='delivery_address_2',
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apt_no', models.TextField(blank=True, max_length=255, null=True, verbose_name='Apartment number')),
                ('address', models.TextField(max_length=255, verbose_name='Address')),
                ('additional_info', models.TextField(blank=True, max_length=255, null=True, verbose_name='Additional Information')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
