# Generated by Django 5.0.1 on 2024-02-17 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_delivery_address_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='additional_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='apt_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apartment number'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to='profiles.profile'),
        ),
    ]
