# Generated by Django 5.0.1 on 2024-02-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_deliveryaddress_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='region',
            field=models.CharField(default='Anambra', max_length=100, verbose_name='City'),
        ),
    ]
