# Generated by Django 5.0.1 on 2024-02-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_deliveryaddress_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='home_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='additional_info',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Additional Information'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='Your Home Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='apt_no',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Apartment number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='region',
            field=models.CharField(default='Anambra', max_length=100, verbose_name='Region'),
        ),
    ]
