# Generated by Django 5.0.1 on 2024-02-14 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_rating_product'),
        ('shop', '0006_remove_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rating', to='shop.product', verbose_name='Product being rated'),
        ),
    ]
