# Generated by Django 5.0.1 on 2024-01-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_colors_color_rename_screensizes_screensize_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
