# Generated by Django 5.0.1 on 2024-02-16 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_alter_rating_comment_alter_rating_rating'),
        ('shop', '0006_remove_product_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ratings.rating',),
        ),
    ]
