# Generated by Django 5.0.1 on 2024-01-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.TextField(choices=[('Email', 'Email'), ('Google', 'Google'), ('Facebook', 'Facebook')], default='Email', max_length=20),
        ),
    ]
