# Generated by Django 5.0.1 on 2024-02-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
        ('profiles', '0005_alter_deliveryaddress_additional_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Delivery Addresses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('profiles.deliveryaddress',),
        ),
    ]
