# Generated by Django 5.0.1 on 2024-02-26 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0004_alter_cart_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.TextField(choices=[('PAYPAL', 'PAYPAL'), ('GOOGLEPAY', 'GOOGLEPAY'), ('APPLEPAY', 'APPLEPAY'), ('BANK_TRANSFER', 'BANK_TRANSFER')], default='BANK_TRANSFER')),
                ('transaction_id', models.TextField(blank=True, help_text='Transaction ID of Payment Provider', max_length=250, null=True)),
                ('currency', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('successful', 'successful'), ('cancelled', 'cancelled')], default='pending')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('delivery_address', models.TextField(max_length=255, verbose_name='Delivery Address')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.TextField(choices=[('PAYPAL', 'PAYPAL'), ('GOOGLEPAY', 'GOOGLEPAY'), ('APPLEPAY', 'APPLEPAY'), ('BANK_TRANSFER', 'BANK_TRANSFER')], default='BANK_TRANSFER')),
                ('currency', models.CharField(max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.TextField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('successful', 'successful'), ('cancelled', 'cancelled'), ('shipped', 'shipped')], default='pending')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='placed_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerifiedOrder',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_orders', to='order.payment')),
                ('placed_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='verified_orders', to='order.placeorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
