# Generated by Django 5.0.1 on 2024-02-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeorder',
            old_name='cart',
            new_name='items',
        ),
    ]
