# Generated by Django 5.0.1 on 2024-02-28 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_cart_placeorder_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerifiedOrder',
            new_name='Order',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.TextField(choices=[('PAYSTACK', 'PAYSTACK'), ('GOOGLEPAY', 'GOOGLEPAY'), ('APPLEPAY', 'APPLEPAY'), ('BANK_TRANSFER', 'BANK_TRANSFER')], default='BANK_TRANSFER'),
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='payment_method',
            field=models.TextField(choices=[('PAYSTACK', 'PAYSTACK'), ('GOOGLEPAY', 'GOOGLEPAY'), ('APPLEPAY', 'APPLEPAY'), ('BANK_TRANSFER', 'BANK_TRANSFER')], default='BANK_TRANSFER'),
        ),
    ]
